leaseYXZ500/leaseYXZ500/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import  re_path
from Z500 import views
from Z500.tools import viewss
from . import  testdb


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^ifc/index$', views.index),
    re_path(r'^approve/pro/add$', viewss.testApproveFlow),
    re_path(r'^approve/', viewss.testApprove),
    re_path(r'^paymentApprove/pro/add$', viewss.testPaymentApproveFlow),
    re_path(r'^paymentApprove/', viewss.testPaymentApprove),

    re_path(r'^data/pro/add$', viewss.test_add_pro),
    re_path(r'^data/', viewss.testMakeData),
    re_path('^demo$', views.demo),
    re_path(r'^ifc/', viewss.test_qq),
    re_path(r'^contract/pro/add$', viewss.testContractAdd),
    re_path(r'^contract/', viewss.testContract),
    re_path(r'^middleCode/pro/add$', viewss.testMiddleCodeQuery),
    re_path(r'^middleCode/', viewss.testMiddleCode),
    re_path(r'^direct/', viewss.testDirect),
    re_path(r'^payment/pro/add$', viewss.testPaymentAdd),
    re_path(r'^payment/', viewss.testPayment),
    re_path(r'^checkMiddleCode/pro/add$', viewss.testMiddleCodeCheck),
    re_path(r'^checkMiddleCode/', viewss.testCheckMiddleCode),
    re_path(r'^credit/pro/add$', viewss.testCreditReport),
    re_path(r'^credit/', viewss.testCredit),
    re_path(r'^token/pro/add$', viewss.testGetToken),
    re_path(r'^token/', viewss.testToken),

    re_path(r'^id/pro/add$', viewss.testGetId),
    re_path(r'^id/', viewss.testId),

    re_path(r'^user/pro/add2$', viewss.testRestPass),
    re_path(r'^user/pro/add$', viewss.testGetUser),
    re_path(r'^user/', viewss.testUser),

    # re_path(r'^pro/add', views.add_pr),
    # re_path(r'^pro/submit', views.proSubmit),
    # re_path(r'^testdb$', testdb.testdb),
]

leaseYXZ500/Z500/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


# class Test(models.Model):
#     name = models.CharField(max_length=20)
#
#     class Meat:
#         app_label = "test"
#         manage = True

class Sys_param_config(models.Model):
    config_type = models.CharField(max_length=20)
    config_value = models.CharField(max_length=20)
    class Meta:
        managed = False
        # app_label = "ifc_uat"
        db_table = "sys_param_config"

class Auth_group(models.Model):
    name = models.CharField(max_length=20)
    class Meta:
        managed = False
        # app_label = "ifc_uat"
        db_table = "auth_group"

class Biz_flow_info(models.Model):
    task_id = models.CharField(max_length=20)
    business_key = models.CharField(max_length=20)
    assignee = models.CharField(max_length=20)
    task_name = models.CharField(max_length=20)
    class Meta:
        managed = False
        # app_label = "ifc_uat"
        db_table = "biz_flow_info"

class Auth_user_sync_record(models.Model):
    AUTH_USER_SYNC_ID = models.IntegerField(primary_key=True)
    USER_ID = models.CharField(max_length=20)
    UC_SYNC_ID = models.CharField(max_length=20)
    class Meta:
        managed = False
        # app_label = "xiaowei_uat"
        db_table = "auth_user_sync_record"


class Z500_test(models.Model):
    name = models.CharField(max_length=20)
    # count = models.IntegerField(max_length=20)
    projectNo = models.CharField(max_length=20)
    node = models.CharField(max_length=20)
    type = models.CharField(max_length=20)
    create_time = models.DateTimeField(max_length=6)
    env = models.CharField(max_length=20)

    class Meta:
        managed = False
        # app_label = "xiaowei_uat"
        db_table = "z500_test"



class Pay_main_info(models.Model):

    pay_info_no = models.CharField(max_length=20)
    pay_main_no = models.CharField(max_length=20)
    project_no = models.CharField(max_length=20)
    proj_trades_id = models.IntegerField(max_length=100)

    class Meta:
        managed = False
        db_table = "pay_main_info"


class Proj_main_info(models.Model):

    project_no = models.CharField(max_length=20)
    creator_id = models.CharField(max_length=20)


    class Meta:
        managed = False
        db_table = "proj_main_info"


class Proj_trades_supplier(models.Model):
    project_no = models.CharField(max_length=20)
    proj_trades_id = models.IntegerField(max_length=100)
    settle_mode = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = "proj_trades_supplier"

class Credit_auth(models.Model):
    '''征信授权表'''
    credit_customer_no = models.CharField(max_length=20)
    credit_customer_type = models.CharField(max_length=20)
    project_no = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = "Credit_auth"

class Proj_cust_enterprise_info(models.Model):
    '''项目-企业信息表'''
    id_card_no = models.CharField(max_length=20)
    project_no = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = "proj_cust_enterprise_info"

class Proj_cust_enterprise_related_info(models.Model):
    '''项目-企业关键人信息表'''
    id_card_no = models.CharField(max_length=20)
    project_no = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = "Proj_cust_enterprise_related_info"


class Proj_cust_personal_info(models.Model):
    '''项目-个人信息表'''
    id_card_no = models.CharField(max_length=20)
    project_no = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = "Proj_cust_personal_info"

class Project_manage(models.Model):
    '''项目管理'''
    PROJECT_MANAGE_ID = models.CharField(max_length=20,primary_key=True)
    PROJECT_NO = models.CharField(max_length=20)
    PROJECT_GROUP_ID = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = "Project_manage"


class Project_manage_group(models.Model):
    '''项目管理组(多交易结构)'''
    PROJECT_GROUP_ID = models.CharField(max_length=20,primary_key=True)
    SOURCE_SYS_RELA_NO = models.CharField(max_length=20)
    EFFECT_STATUS = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = "Project_manage_group"

class Uaa_user(models.Model):
    '''用户表'''
    id = models.CharField(max_length=20,primary_key=True)
    login = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = "Uaa_user"



#
# class Teacher(models.Model):
#     name = models.CharField(max_length=30)
#     age = models.IntegerField(blank=True, null=True)
#     tel = models.CharField(max_length=30)
#
#     class Meta:
#         managed = False
#         # app_label = "xiaowei_uat"
#         db_table = "Teacher"

class MeetingRoom(models.Model):
    name = models.CharField(max_length=100, unique=True)
    capacity = models.IntegerField()

    def __str__(self):
        return self.name

class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(MeetingRoom, on_delete=models.CASCADE)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()

    def __str__(self):
        return f"{self.room} - {self.date} {self.start_time}-{self.end_time}"

leaseYXZ500/Z500/views.py
#encoding='utf-8'

import json
import time
from urllib3.util.retry import Retry
from requests.adapters import HTTPAdapter
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
import requests
import jsonpath
import sys

# Create your views here.

url = 'http://sit-vrip.msfl.com.cn/'

req = requests.session()

def api(**kwargs):
    global headers_uat
    global url
    global req
    retries = Retry(total=2,
                    status_forcelist=[400, 500, 502, 503, 504])
    url_new = url +kwargs.get("url")
    kwargs.pop("url")
    req.mount('http://', HTTPAdapter(max_retries=retries))
    req.mount('https://', HTTPAdapter(max_retries=retries))
    res = req.request(url =url_new, verify=True, headers=headers_uat, **kwargs).json()
    print(url_new,res)
    return res

def login(custName):
    login = {"jxw":"d71166f649e82dd056e75bc793ce9c0a6cc1258930cf80a5111b49913ee84f80",
             "fht":"89ae7733c591b618bf21cf5f4a48e40dbf79c33495c94c91fbeccd843b141a81",
             "zll":"5d8fbee0cb6509d6252c977283b09c52f1fc17c6bfa1742c00f9f1177be256dc",
             "Huangzuning":"6a57bc9c2845a449f2873adc510ca4244c310c1f604d19946af6264003fafdbb",
             "xzw":"c3c9773841309436de74b77a52020ab815052e1b414d3765e81ba974f2b69970"}
    url1 = 'http://test-vrip.msfl.com.cn/uaa/login-psms-code'
    data = {"password":login[custName],"username":custName}
    res1 = requests.request('POST', url1, json=data,verify=True)
    print(res1)
    url2 = 'http://test-vrip.msfl.com.cn/auth/login-sms'
    data = {"code":"123456","rememberMe":True,"username":"%s"%custName}
    res2 = requests.request('POST', url2, json=data, verify=True).json()
    return res2

def pro_page():
    url = 'ifc/api/credit-auth/project/page'
    data = {
            "current": 1,
            "size": 20,
            "leaseName": "",
            "statusCode": "000000"
        }
    res = api(method ="POST", url=url,  json = data)
    return res

def preQuery(projectNo):
    '''预审初始化'''
    url = 'ifc/api/pre-approval/init?projectNo=%s'%projectNo
    res = api(method = "GET", url = url)
    return res

def add_pro(lesaseName):
    '''新建项目'''
    url = 'ifc/api/credit-auth/createProj?leaseName=%s' % lesaseName
    res = api(method="GET", url=url)
    return res

def getPro(projectNo):
    url = 'ifc/api/credit-auth/project/query/detail?projectNo=%s'%projectNo
    res = api(method ="GET", url=url)
    return res

def creditAuthSave(projectNo):
    '''创建征信授权'''
    url = 'ifc/callback/credit-auth/save'
    data_fht = {
        "businessName": "测试软创",
        "businessAddress": None,
        "businessCreditCode": "911101083398346103",
        "businessStartDate": None,
        "businessTermEndDate": None,
        "projectNo": projectNo,
        "preAprlCode": projectNo +"202308031008597437",
        "creditCustomerType": "ENT",
        "creditCustomerName": "范怀通",
        "creditCustomerTel": "13020117356",
        "creditCustomerNo": "412702199005284111",
        "creditCustomerIdType": None,
        "certificateValidStartDate": None,
        "certificateValidEndDate": None,
        "identityType": "法人",
        "accountManager": "fht",
        "creditCustomerSex": None,
        "creditCustomerAddress": "深圳市罗湖区深南东路5047号平安银行总行",
        "custCenterCode": None,
        "source": None
    }
    res = api(method='POST', url=url, json=data_fht)
    time.sleep(1)
    data_jxw = {
            "businessName": "测试Z500公司J2",
            "businessAddress": None,
            "businessCreditCode": "91310000NRNL32PU3J",
            "businessStartDate": None,
            "businessTermEndDate": None,
            "projectNo": projectNo,
            "preAprlCode": projectNo +"202308021551111545",
            "creditCustomerType": "ENT",
            "creditCustomerName": "季晓伟",
            "creditCustomerTel": "15705101126",
            "creditCustomerNo": "320683199410302714",
            "creditCustomerIdType": None,
            "certificateValidStartDate": None,
            "certificateValidEndDate": None,
            "identityType": "法人",
            "accountManager": "jxw",
            "creditCustomerSex": None,
            "creditCustomerAddress": "上海",
            "custCenterCode": None,
            "source": None
        }
    res = api(method='POST', url=url, json=data_jxw)

def creditAuthBack(projectNo):
    '''征信授权完成'''
    url = 'ifc/callback/credit-auth/signOffCallback'
    data_fht = {
        "preAprlCode": projectNo + "202308031008597437",
        "ssqContractId": "3374570986154108930",
        "businessLicenceFileId": "9015937627781681152",
        "faceFileId": "9121959342059274240",
        "backFileId": "9121869907951071232"
    }
    res = api(method='POST', url=url, json=data_fht)
    data_jxw =  {
        "backFileId": "9020716865953443840",
        "businessLicenceFileId": "6868482948483813376",
        "faceFileId": "9020792603410939904",
        "preAprlCode": projectNo + "202308021551111545",
        "ssqContractId": "3374018567829595143"
    }
    res = api(method='POST', url=url, json=data_jxw)

def taskCompleteInit(taskid):
    '''初始化流程'''
    url = 'ifc/api/flow/task-complete/init?taskId=%s'%taskid
    res = api(method='GET', url=url)

def proSubmit(projectNo):
    '''预审提交'''
    url = 'ifc/api/pre-approval/submit'
    res_query = preQuery(projectNo)
    data={
        "projectNo": projectNo,
        "customerList": [
            {
                "id": jsonpath.jsonpath(res_query,'$..id')[0],
                "creditCustomerType": jsonpath.jsonpath(res_query,'$..creditCustomerType')[0],
                "creditCustomerTypeName": jsonpath.jsonpath(res_query,'$..creditCustomerTypeName')[0],
                "creditCustomerName": jsonpath.jsonpath(res_query,'$..creditCustomerName')[0],
                "creditCustomerNo": jsonpath.jsonpath(res_query,'$..creditCustomerNo')[0],
                "creditCustomerIdType": jsonpath.jsonpath(res_query,'$..creditCustomerIdType')[0],
                "creditCustomerIdTypeName": jsonpath.jsonpath(res_query,'$..creditCustomerIdTypeName')[0],
                "roleType": "6"
            },
            {
                "id": jsonpath.jsonpath(res_query,'$..id')[1],
                "creditCustomerType": jsonpath.jsonpath(res_query,'$..creditCustomerType')[1],
                "creditCustomerTypeName": jsonpath.jsonpath(res_query,'$..creditCustomerTypeName')[1],
                "creditCustomerName": jsonpath.jsonpath(res_query,'$..creditCustomerName')[1],
                "creditCustomerNo": jsonpath.jsonpath(res_query,'$..creditCustomerNo')[1],
                "creditCustomerIdType": jsonpath.jsonpath(res_query,'$..creditCustomerIdType')[1],
                "creditCustomerIdTypeName": jsonpath.jsonpath(res_query,'$..creditCustomerIdTypeName')[1],
                "roleType": "1"
            },
            {
                "id": jsonpath.jsonpath(res_query,'$..id')[2],
                "creditCustomerType": jsonpath.jsonpath(res_query,'$..creditCustomerType')[2],
                "creditCustomerTypeName": jsonpath.jsonpath(res_query,'$..creditCustomerTypeName')[2],
                "creditCustomerName": jsonpath.jsonpath(res_query,'$..creditCustomerName')[2],
                "creditCustomerNo": jsonpath.jsonpath(res_query,'$..creditCustomerNo')[2],
                "creditCustomerIdType": jsonpath.jsonpath(res_query,'$..creditCustomerIdType')[2],
                "creditCustomerIdTypeName": jsonpath.jsonpath(res_query,'$..creditCustomerIdTypeName')[2],
                "roleType": "2"
            },
            {
                "id": jsonpath.jsonpath(res_query,'$..id')[3],
                "creditCustomerType": jsonpath.jsonpath(res_query,'$..creditCustomerType')[3],
                "creditCustomerTypeName": jsonpath.jsonpath(res_query,'$..creditCustomerTypeName')[3],
                "creditCustomerName": jsonpath.jsonpath(res_query,'$..creditCustomerName')[3],
                "creditCustomerNo": jsonpath.jsonpath(res_query,'$..creditCustomerNo')[3],
                "creditCustomerIdType": jsonpath.jsonpath(res_query,'$..creditCustomerIdType')[3],
                "creditCustomerIdTypeName": jsonpath.jsonpath(res_query,'$..creditCustomerIdTypeName')[3],
                "roleType": "3"
            }
        ],
        "productType": "LS-DFL",
        "productNo": "LeaseYXZ300"
    }
    res = api(method ="POST", url=url,  json = data)
    return res_query

def opinionSumit(taskId):
    taskCompleteInit(taskId)
    '''提交审批意见'''
    url = 'ifc/api/flow/task-complete'
    data = {
            "remind": "测试同意222",
            "taskId": taskId
        }
    time.sleep(3)
    res = api(method = 'POST', url =url,json = data)

def custEnterpriseQuery(projectNo):
    '''客户信息-承租人-查询'''
    url = 'ifc/api/proj_cust_enterprise_info/queryByCondition'
    data = {
        "projectNo": projectNo
    }
    res = api(method = 'POST', url =url,json = data)
    return res

def custEnterpriseSave(projectNo):
    res_query = custEnterpriseQuery(projectNo)
    url = 'ifc/api/proj_cust_enterprise_info/save'
    data = {
            "id": jsonpath.jsonpath(res_query,'$..id')[0],
            "projectNo": projectNo,
            "sourceId": jsonpath.jsonpath(res_query,'$..sourceId')[0],
            "projectCustomerInfoId": jsonpath.jsonpath(res_query,'$..projectCustomerInfoId')[0],
            "roleType": jsonpath.jsonpath(res_query,'$..roleType')[0],
            "name": jsonpath.jsonpath(res_query,'$..name')[0],
            "idCardType": jsonpath.jsonpath(res_query,'$..idCardType')[0],
            "idCardTypeName":  jsonpath.jsonpath(res_query,'$..idCardTypeName')[0],
            "idCardNo": jsonpath.jsonpath(res_query,'$..idCardNo')[0],
            "phoneNumber": "15705101126",
            "country": "156",
            "countryName": "中国",
            "interIndustryClassifyOne": "A",
            "interIndustryClassifyTwo": "A01",
            "interIndustryClassifyThree": "A011",

leaseYXZ500/Z500/templates/demo.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>demo样式</title>-->
<!--</head>-->
<!--<body>-->

<!--<p>-->
<!--    <h4> 这是我的博客地址，可以百度搜：上海-悠悠 </h4>-->
<!--    <a href="https://www.cnblogs.com/yoyoketang/" target="_blank" >上海-悠悠-博客园</a>-->
<!--    <hr>-->
<!--    <h4> 《python自动化框架pytest》 </h4>-->
<!--    <p>pytest是最强大最好用的python自动化框架，没有之一。本书详细讲解pytest框架使用方法，fixture功能是pytest的精髓，书中有详细的案例讲解。<br>-->
<!--        另外最后会有项目实战代码，灵活用到selenium自动化项目上。<br>-->
<!--        pytest交流群874033608-->

<!--    </p>-->
<!--    <a href="https://yuedu.baidu.com/ebook/902224ab27fff705cc1755270722192e4536582b" target="_blank" >百度阅读地址点此</a>-->
<!--</p>-->
<!--    <p>{{cust}}</p>-->

</body>
</html>
{% load static %}

<link rel="stylesheet" href="{% static 'css/toastr.min.css' %}">
    <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'css/toastr.min.js' %}"></script>

<body>

<div class="container">
    <button class="btn btn-info">info</button>
    <button class="btn btn-success">success</button>
    <button class="btn btn-warning">warning</button>
    <button class="btn btn-danger" type="submit" >error</button>


<!--    <input type="submit" value="提交">-->


</div>


</body>

<script>
    //toastr消息
    $(".btn-info").click(function(){
        toastr.info('info 消息提示')
    });
    $(".btn-success").click(function(){
        toastr.success('操作成功！')
    });
    $(".btn-warning").click(function(){
        toastr.warning('警告内容！')
    });
    $(".btn-danger").click(function(){
        toastr.error('服务器异常！')
        toastr.error('警告内容！')

    });
</script>

<div class="container">
    <button id="get_btn" class="btn btn-info">发get请求</button>
    <button id="post_btn" class="btn btn-info">发post请求</button>
</div>
    客户经理: <input type="text" name="number1"> <br>



<script>
    $("#get_btn").click(function(){
            var custName = $('input[name="number1"]').val()
            toastr.error('服务器异常！');
            $.get('pro/add',
                    {
                        custName: custName,
                        node: "1",
                        guarantor:"2"
                    },
                  function(data, status) {
                      alert("状态："+ status + ",body:" + JSON.stringify(data))
                  })
    })
</script>

leaseYXZ500/Z500/templates/get_contract.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>直500</title>
</head>
<body>


<h4> 直500 </h4>

</body>
</html>
{% load static %}

<link rel="stylesheet" href="{% static 'css/toastr.min.css' %}">
    <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
    <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'css/toastr.min.js' %}"></script>


<!--<head>-->
<!--    <link href="/static/bootstarp/css/bootstrap.min.css" rel="stylesheet">-->
<!--    <link rel="stylesheet" href="/static/bootstrap-select/dist1.12.4/css/bootstrap-select.min.css">-->
<!--    <script src="/static/bootstarp/jquery/jquery3.2.1.js"></script>-->
<!--    <script src="/static/bootstarp/js/bootstrap.min.js"></script>-->
<!--    <script src="/static/bootstrap-select/dist1.12.4/js/bootstrap-select.min.js"></script>-->
<!--</head>-->

<!--<body>-->

<!--<div class="container">-->
<!--    <button class="btn btn-info">info</button>-->
<!--    <button class="btn btn-success">success</button>-->
<!--    <button class="btn btn-warning">warning</button>-->
<!--    <button class="btn btn-danger" type="submit" >error</button>-->


<!--&lt;!&ndash;    <input type="submit" value="提交">&ndash;&gt;-->


<!--</div>-->


<!--</body>-->

<!--<script>-->
<!--    //toastr消息-->
<!--    $(".btn-info").click(function(){-->
<!--        toastr.info('info 消息提示')-->
<!--    });-->
<!--    $(".btn-success").click(function(){-->
<!--        toastr.success('操作成功！')-->
<!--    });-->
<!--    $(".btn-warning").click(function(){-->
<!--        toastr.warning('警告内容！')-->
<!--    });-->
<!--    $(".btn-danger").click(function(){-->
<!--        toastr.error('服务器异常！')-->
<!--        toastr.error('警告内容！')-->

<!--    });-->
<!--</script>-->

<div class="container">

<!--    客户经理: <input type="text" name="custName"> <br>-->
    <th><label for="id_custName">客户经理:</label></th>
    <select class="selectcust" title="请选择">
        <option value="jxw" title="jxw">jxw</option>
        <option value="xzw" title="xzw">xzw</option>
        <option value="cm" title="cm">cm</option>
        <option value="fht" title="fht">fht</option>
        <option value="zll" title="zll">zll</option>
    </select><br><br>





    <th><label for="id_env">测试环境:</label></th>
    <select class="selectenv" title="请选择">
        <option value="test" title="test">uat</option>
        <option value="sit" title="sit">sit</option>
    </select><br>

    <p> 合同编号：<input type="text" name="payMainNo"> 此项目已授信审批通过且无担保方</p>

<!--    <th><label for="id_guarantor">是否需要担保方:</label></th>-->
<!--    <select class="selectguarantor" title="请选择">-->
<!--        <option value="2" title="2">否</option>-->
<!--        <option value="1" title="1">是</option>-->
<!--        <option value="3" title="3">多个</option>-->
<!--    </select><br><br>-->

<!--    是否需要担保方（非必填,1:是,2:否,默认否）: <input type="text" name="guarantor"> <br><br>-->
<!--    测试环境（非必填,sit,test,默认test）: <input type="text" name="env"> <br><br>-->
<!--     <p> 节点：<input type="radio" name="node" value="0">待授信申请（未填写）-->
<!--         <input type="radio" name="node" value="1">待授信申请（已填写）-->
<!--         <input type="radio" name="node"  value="2">业务主管审批-->
<!--          <p> 节点：<input type="radio" name="node"  value="3">区域负责人审批-->
<!--        <input type="radio" name="node"  value="4">评审经理审批-->
<!--         <input type="radio" name="node"  value="5">评审主管审批-->
<!--         <input type="radio" name="node"  value="6">有权人审批-->
<!--         <input type="radio" name="node"  value="7">审批通过-->

<!--     </p><br>-->

    <button id="get_btn" class="btn btn-info">提交</button>
<!--    <button id="post_btn" class="btn btn-info">发post请求</button>-->
</div>

<!--<script>-->
<!--    $("#get_btn").click(function(){-->
<!--            var custName = $('input[name="custName"]').val();-->
<!--            var guarantor = $('input[name="guarantor"]').val()-->
<!--            var node = $('input[name="node"]').val()-->
<!--            toastr.success('提交成功,正在执行脚本,请耐心等待,大概8分钟');-->
<!--            $.get('pro/add',-->
<!--                    {-->
<!--                        custName: custName,-->
<!--                        node: "1",-->
<!--                        guarantor:"2"-->
<!--                    },-->
<!--                  function(data, status) {-->
<!--                      alert("状态："+ status + ",body:" + JSON.stringify(data))-->
<!--                      alert("状态: "+ status + ", " + JSON.stringify(data))-->
<!--                  }).fail(function() {-->
<!--                      alert('接口请求失败！');-->
<!--    })-->
<!--</script>-->





<script>
    $("#get_btn").click(function(){
        var custName = $(".selectcust").val();
        var payMainNo = $('input[name="payMainNo"]').val();
        var env = $(".selectenv").val();
<!--        var node = $('input[name="node"]').serialize();-->
        toastr.success('提交成功,正在执行脚本,请耐心等待,大概5分钟');
        $.ajax({
            url: "pro/add",
            type: "GET",  //默认值: "GET"请求方式 ("POST" 或 "GET")
            data: {
                        custName: custName,
                        payMainNo: payMainNo,
                        env: env,
<!--                        node: node-->
                    },
            dataType:"json",   //服务器返回的类型json,xml,text,html等
            success: function(result, status, xhr){      // 回调结果，如果成功

                        if(result.code == 0){    //判断状态码
                             // code为0，弹出成功提示
                             alert("请求成功："+JSON.stringify(result))}
                        else {
                             alert("请求失败："+JSON.stringify(result))
                            }
                    },
            error: function(result, xhr, status, error) {
                        alert("接口返回状态："+ status)
                     }
            });
        })
</script>

leaseYXZ500/Z500/templates/get_demo.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>直500</title>
</head>
<body>
<!--<p>请输入你的项目编号</p>-->

<!--<form action="/result" method="get">-->
<!--    编号: <input type="text" name="id"> <br>-->
<!--    <br>-->
<!--    <input type="submit" value="提交">-->
<!--</form>-->


<h4> 直500 </h4>
<form action="/pro/add" method="get">
    客户经理: <input type="text" name="custName"> <br>
<!--    承租人名称: <input type="text" name="lesaseName"> <br>-->
<!--    项目编号（非必填）: <input type="text" name="projectNo"> <br>-->
    是否需要担保方（非必填,1:是,2:否,默认否）: <input type="text" name="guarantor"> <br>
     <p> 节点：<input type="radio" name="node" value="0">待授信申请
         <input type="radio" name="node"  value="1">业务主管审批
<!--         <input type="radio" name="node"  value="2">区域负责人审批-->
         <input type="radio" name="node"  value="3">评审经理审批
         <input type="radio" name="node"  value="4">评审主管审批
         <input type="radio" name="node"  value="5">有权人审批
         <input type="radio" name="node"  value="6">审批通过

     </p>
    <br>
    <input type="submit" value="提交">
</form>



</body>
</html>