demo1/demo1/urls.py
from django.urls import re_path
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from apptest import views
urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    # 用户登录
    re_path(r'^login/',views.acc_login),
    # 展示预订信息
    re_path(r'^index/',views.index),
    # 极验滑动验证码 获取验证码的url
    re_path(r'^pc-geetest/register', views.get_geetest),
    # media相关的路由设置
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
    # 处理预订请求
    re_path(r'^book/',views.book),
    # 首页
    re_path(r'^home/',views.home),
    # 注销
    re_path(r'^logout/',views.acc_logout),
    # 用户注册
    re_path(r'^reg/',views.reg),
    # 临时测试
    re_path(r'^test/',views.test),
    # 修改密码
    re_path(r'^change_password/',views.change_password),

    # about
    re_path(r'^about/',views.about),


]

demo1/apptest/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class UserInfo(AbstractUser):
    tel = models.CharField(max_length=32,verbose_name="电话")
    avatar = models.FileField(upload_to="avatars/", default="avatars/timg.jpg", verbose_name="头像")


class Room(models.Model):
    """会议室表"""
    caption = models.CharField(max_length=32,verbose_name="会议室名称")
    num = models.IntegerField(verbose_name="容纳人数")  # 容纳人数

    def __str__(self):
        return self.caption

    class Meta:
        verbose_name = "会议室信息"
        verbose_name_plural = verbose_name


class Book(models.Model):
    """会议室预订"""
    user = models.ForeignKey(to="UserInfo",on_delete=models.CASCADE)
    room = models.ForeignKey(to="Room",on_delete=models.CASCADE)
    date = models.DateField()
    time_choice = (
        (1, "8:00"),
        (2, "9:00"),
        (3, "10:00"),
        (4, "11:00"),
        (5, "12:00"),
        (6, "13:00"),
        (7, "14:00"),
        (8, "15:00"),
        (9, "16:00"),
        (10, "17:00"),
        (11, "18:00"),
        (12, "19:00"),
        (13, "20:00"),
        (14, "21:00"),
        (15, "22:00"),
        (16, "23:00"),
    )

    time_id = models.IntegerField(choices=time_choice)

    def __str__(self):
        return str(self.user)+"预定了"+str(self.room)

    class Meta:
        verbose_name = "预定信息"
        verbose_name_plural = verbose_name
        unique_together = (
            ("room","date","time_id"),  # 这三个字段联合唯一，防止重复预订
        )

demo1/apptest/forms.py
"""
BBS用到的form组件
"""
from django import forms
from django.core.exceptions import ValidationError
from apptest import models


# 定义注册类
class RegForm(forms.Form):
    username = forms.CharField(
        max_length=32,
        label="用户名",
        error_messages={
            "max_length": "用户名最大32位",
            "required": "用户名不能为空",
        },
        widget=forms.widgets.TextInput(
            attrs={"class": "form-control"}),
        )
    email = forms.EmailField(
        label="邮箱",

        widget=forms.widgets.EmailInput(
            attrs={"class": "form-control"},
        ),
        error_messages={
            "invalid": "邮箱格式错误",
            "required": "邮箱不能为空",
        }
    )
    password = forms.CharField(
        min_length=6,
        label="密码",
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"}
        ),
        error_messages={
            "min_length": "密码至少6位",
            "required": "密码不能为空",
        }
    )
    re_password = forms.CharField(
        min_length=6,
        label="确认密码",
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control"}
        ),
        error_messages={
            "min_length": "密码至少6位",
            "required": "确认密码不能为空",
        }
    )

    # 重写username字段的局部钩子函数，对username字段检验
    def clean_username(self):
        username = self.cleaned_data.get("username")
        is_exist = models.UserInfo.objects.filter(username=username)
        if is_exist:
            # 用户名已经存在
            self.add_error("username", ValidationError("用户名已经存在"))
        else:
            return username

    # 重写全局的钩子函数,对确认密码做校验
    def clean(self):
        password = self.cleaned_data.get("password")
        re_password = self.cleaned_data.get("re_password")
        if re_password and re_password != password:
            self.add_error("re_password", ValidationError("两次密码不一致"))


# 定义修改密码类
class ChangePwdForm(forms.Form):
    password = forms.CharField(
        min_length=6,
        label="旧密码",

        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control","placeholder":"请输入旧密码"}
        ),
        error_messages={
            "min_length": "密码至少6位",
            "required": "密码不能为空",
        }
    )
    new_password = forms.CharField(
        min_length=6,
        label="新密码",
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control","placeholder":"请输入新密码"}
        ),
        error_messages={
            "min_length": "密码至少6位",
            "required": "新密码不能为空",
        }
    )

    confirm_password = forms.CharField(
        min_length=6,
        label="确认密码",
        widget=forms.widgets.PasswordInput(
            attrs={"class": "form-control","placeholder":"请输入确认密码"}
        ),
        error_messages={
            "min_length": "密码至少6位",
            "required": "确认密码不能为空",
        }
    )

    # 重写全局的钩子函数,对确认密码做校验
    def clean(self):
        password = self.cleaned_data.get("new_password")
        re_password = self.cleaned_data.get("confirm_password")
        if re_password and re_password != password:
            self.add_error("confirm_password", ValidationError("两次密码不一致"))

demo1/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>关于系统</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <style>
        .mui-content {

            background: url("/static/img/full_back.png") bottom center no-repeat #efeff4;

            background-size: 100% 100%;

            width: 800px;

            height: 800px;

        }
    </style>
</head>
<body class="mui-content">
<div class="pull-right">
    <a href="/home/">返回首页</a>
</div>
<br>
<br>
<div class="container text-center" >
    <div class="row">
        <div class="col-md-6 col-lg-offset-4">
            <div class="panel panel-default ">
                <div class="panel-heading text-center" style="color: rebeccapurple">会议室预订系统</div>
                <div class="panel-body">
                    众多的会议室，怎样避免会议冲突？怎样实现非人工管理？怎样方便快捷的预定会议？怎样及时通知与会人员等等？总之，怎样才能提升会议室资源的利用效率？
                    1.快速查询：系统采用B/S架构，随时随地通过网络登录到服务端查询会议室的预定情况，会议资源情况； 2.轻松预定：根据自己所需会议资源和会议室使用情况统计，轻松预定适合自己的会议室。
                </div>
            </div>
        </div>
    </div>
</div>


</body>
</html>

demo1/templates/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">

</head>
<body>
<div class="container">
    <div class="row">
        <div class="page-header text-center">
            <h1>会议室预订系统 <small>修改密码</small></h1>
        </div>
        <div class="col-md-4 col-lg-offset-4">
            <form class="form-horizontal" novalidate method="post">
                {% csrf_token %}
                <!--用户名-->
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-4 control-label">用户名</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control text-center" disabled=disabled id="inputEmail3"  value={{ username }}>
                    </div>
                </div>
                <!--旧密码-->
                <div class="form-group">
                    <label for="{{ form_obj.password.id_for_label }}" class="col-sm-4 control-label">原密码</label>
                    <div class="col-sm-8">
                        {{ form_obj.password }}
                        <span class="help-block" style="color: red">{{ form_obj.password.errors.0 }}</span>
                    </div>
                </div>
                <!--新密码-->
                <div class="form-group">
                    <label for="{{ form_obj.new_password.id_for_label }}" class="col-sm-4 control-label">新密码</label>
                    <div class="col-sm-8">
                        {{ form_obj.new_password }}
                        <span class="help-block" style="color: red">{{ form_obj.new_password.errors.0 }}</span>

                    </div>
                </div>
                <!--确认密码-->
                <div class="form-group">
                    <label for="{{ form_obj.confirm_password.id_for_label }}" class="col-sm-4 control-label">确认新密码</label>
                    <div class="col-sm-8">
                        {{ form_obj.confirm_password }}
                        <span class="help-block" style="color: red">{{ form_obj.confirm_password.errors.0 }}</span>

                    </div>
                </div>
                <!--修改密码-->
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8">
                        <span id="msg" msg="{{ msg }}"></span>
                        <button type="submit" class="btn btn-info">确定修改</button>
                        <a href="/home/" class="btn btn-warning pull-right">返回首页</a>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>
<script src="/static/js/jquery-3.3.1.min.js"></script>
<script>
     // 将所有的input框绑定获取焦点的事件，将所有的错误信息清空
    $("form input").focus(function () {
        console.log($(this).next().text());
        $(this).next().text("");
    });
    // 修改密码成功就跳转登录页面
    var msg = $("#msg").attr("msg");
    if(msg){
        location.href=msg;
    }
</script>
</body>
</html>

demo1/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>base</title>
     <meta charset="UTF-8">
    <title>会议室预订系统首页</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/datetimepicker/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="/static/CodeSeven-toastr-2.1.4-7-g50092cc/CodeSeven-toastr-50092cc/build/toastr.css">
    <script src="/static/js/jquery-3.3.1.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/datetimepicker/bootstrap-datetimepicker.min.js"></script>
    <script src="/static/datetimepicker/bootstrap-datetimepicker.zh-CN.js"></script>
    <script src="/static/CodeSeven-toastr-2.1.4-7-g50092cc/CodeSeven-toastr-50092cc/build/toastr.min.js"></script>
    <style>
        html, body {

            width: 100%;

            height: 100%;

        }
        .td_active{
            background-color: purple;
        }
        .mui-content {

            background: url("/static/img/full_back.png") bottom center no-repeat #efeff4;

            background-size: 100% 100%;

            width: 100%;

            height: 100%;

        }
    </style>
</head>
<body>
<div >
    <!-- 固定导航栏 -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/home/">会议室预订系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/home/">Home</a></li>
            <li><a href="/about/">About</a></li>
            <li><a href="tencent://message/?uin=3152609963&Site=QQ交谈&Menu=yes" target="blank"><img border="0" src="http://wpa.qq.com/pa?p=1:3152609963:7" alt="图片不正常时显示的文字" width="71" height="24" /></a>

            </li>
          </ul>
            <ul class="nav navbar-nav navbar-right">

                <!--右上角个人中心-->
                <div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                        <ul class="nav navbar-nav navbar-right">
                            {% if request.user.username %}
                                <li><a href="/index/">{{ request.user.username }}</a></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle " data-toggle="dropdown" role="button"
                                       aria-haspopup="true"
                                       aria-expanded="false">个人中心 <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a id="book" href="#" book_ret="{{ book_ret }}">预订信息</a></li>
                                        <li class="text-lowercase text-center">
                                            {% if book_ret %}
                                                <span style="color: yellowgreen;margin-left: -55px"><a
                                                        href="/index/">查看</a></span>
                                            {% else %}

                                                <span class="text-center" style="color: yellowgreen;">暂无</span>
                                            {% endif %}
                                        </li>
                                        <li role="separator" class="divider"></li>
                                        <li><a href="/change_password/">修改密码</a></li>
                                        <li><a href="/logout/">注销</a></li>
                                    </ul>
                                </li>
                            {% else %}
                                <li><a href="/login/">登录</a></li>
                                <li><a href="/reg/">注册</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="/static/img/banner_1.jpg" alt="...">
      <div class="carousel-caption">
        one
      </div>
    </div>
    <div class="item">
      <img src="/static/img/banner_2.jpg" alt="...">
      <div class="carousel-caption">
        two
      </div>
    </div>
    <div class="item">
      <img src="/static/img/banner_3.jpg" alt="...">
      <div class="carousel-caption">
        three
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

</div>
<script>
    var num=$("#book").attr("book_ret");
    if(num){
        toastr.info('您目前有'+num+'个预订信息');
    }else {
        toastr.Warning('您目前没有预订信息');
    }
</script>
</body>
</html>

demo1/templates/reg.html
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>欢迎注册</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <style>
        html, body {

            width: 100%;

            height: 100%;

        }

        #avatar-img {

            width: 80px;
            height: 80px;
        }

        .mui-content {

            background: url("/static/img/reg_bak.jpg") bottom center no-repeat #efeff4;

            background-size: 100% 100%;

            width: 100%;

            height: 100%;

        }
    </style>
</head>
<body>

<div class="container mui-content">
    <h3 class="text-center" style="color: orangered">欢迎注册会议室预订系统</h3>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form novalidate action="/reg/" method="post" autocomplete="off" class="form-horizontal reg-form" enctype="multipart/form-data">
                {% csrf_token %}
                <!--头像-->
                <div class="form-group text-center" style="margin-top: 80px">
                    <label class="col-sm-2 control-label">头像</label>
                    <div class="col-sm-8">
                        <label  for="id_avatar"><img  id="avatar-img" src="/static/img/timg.jpg" alt=""></label>
                        <input  accept="image/*" type="file" name="avatar" id="id_avatar" style="display: none">
                        <span class="help-block"></span>
                    </div>
                </div>
                <!--用户名-->
                <div class="form-group">
                    <label for="{{ form_obj.username.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.username.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.username }}
                        <span class="help-block">{{ form_obj.username.errors.0 }}</span>
                    </div>
                </div>
                <!--邮箱-->
                <div class="form-group">
                    <label for="{{ form_obj.email.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.email.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.email }}
                        <span class="help-block">{{ form_obj.email.errors.0 }}</span>
                    </div>
                </div>
                <!--密码-->
                <div class="form-group">
                    <label for="{{ form_obj.password.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.password.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.password }}
                        <span class="help-block">{{ form_obj.password.errors.0 }}</span>
                    </div>
                </div>
                <!--确认密码-->
                <div class="form-group">
                    <label for="{{ form_obj.re_password.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.re_password.label }}</label>
                    <div class="col-sm-8">
                        {{ form_obj.re_password }}
                        <span class="help-block">{{ form_obj.re_password.errors.0 }}</span>
                    </div>
                </div>
                <!--注册-->
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-12">
                        <button type="button" class="btn btn-success" id="reg-submit">注册</button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <input type="reset" class="btn btn-danger" value="重置">&nbsp;&nbsp;&nbsp;&nbsp;
                        <a class="panel-warning" href="/home/">返回首页</a>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>


<script src="/static/js/jquery-3.3.1.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script>
    // 找到头像的input标签绑定change事件
    $("#id_avatar").change(function () {
        // 1. 创建一个读取文件的对象
        var fileReader = new FileReader();
        // 取到当前选中的头像文件
        // console.log(this.files[0]);
        // 读取你选中的那个文件
        fileReader.readAsDataURL(this.files[0]);  // 读取文件是需要时间的
        fileReader.onload = function () {
            // 2. 等上一步读完文件之后才 把图片加载到img标签中
            $("#avatar-img").attr("src", fileReader.result);
        };
    });
    // AJAX提交注册的数据
    $("#reg-submit").click(function () {
        // 取到用户填写的注册数据，向后端发送AJAX请求
        var formData = new FormData();
        formData.append("username", $("#id_username").val());
        formData.append("password", $("#id_password").val());
        formData.append("re_password", $("#id_re_password").val());
        formData.append("email", $("#id_email").val());
        formData.append("avatar", $("#id_avatar")[0].files[0]);
        formData.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());

        $.ajax({
            url: "/reg/",
            type: "post",
            processData: false,  //告诉Jquery不要处理我的数据
            contentType: false,  //告诉jQuery不要设置content类型
            data: formData,
            success:function (data) {
                if (data.status){
                    // 有错误就展示错误
                    // console.log(data.msg);
                    // 将报错信息填写到页面上
                    $.each(data.msg, function (k,v) {
                        // console.log("id_"+k, v[0]);
                        // console.log($("#id_"+k));
                        $("#id_"+k).next("span").text(v[0]).parent().parent().addClass("has-error");
                    })

                }else {
                    // 没有错误就跳转到指定页面
                    location.href = data.msg;
                }
            }
        })
    });

    // 将所有的input框绑定获取焦点的事件，将所有的错误信息清空
    $("form input").focus(function () {
        $(this).next().text("").parent().parent().removeClass("has-error");
    });
    //给username的input输入框，绑定失去焦点事件，失去焦点后检测用户名是否存在
    $("#id_username").blur(function () {
        // 取到用户填写的值
        var username = $(this).val();
        //发ajax请求
        $.ajax({
            url:"/check_username_exist/",
            type:"get",
            data:{username:username,},
            success:function (data) {
                if(data.status){
                    //有错误，用户名已被注册
                    $("#id_username").next().text(data.msg).parent().parent().addClass("has-error");
                }

            }
        })
    })
</script>
</body>
</html>

demo1/templates/轮播图.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>轮播图</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <script src="/static/js/jquery-1.12.4.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="/static/img/banner_1.jpg" alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="/static/img/banner_2.jpg" alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="/static/img/banner_3.jpg" alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

</body>
</html>